// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"iotPlatform/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/register",
				Handler: UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
