// Code generated by goctl. DO NOT EDIT.
package types

type BaseRequest struct {
	Page int    `json:"page,optional"`
	Size int    `json:",optional"`
	Name string `json:"name,optional"`
}

type DeviceCreateRequest struct {
	Name string `json:"name"`
	Pid  uint64 `json:"product_id`
}

type DeviceDeleteRequest struct {
	Id uint64 `json:"id"`
}

type DeviceListBaisc struct {
	Id             uint64 `json:"id"`
	Name           string `json:"name"`
	Key            string `json:"key"`
	Secret         string `json:"secret"`
	ProductName    string `json:"product_name"`
	LastOnlineTime int64  `json:"last_online_time"`
}

type DeviceListReply struct {
	List  []*DeviceListBaisc `json:"list"`
	Count int64              `json:"count"`
}

type DeviceListRequest struct {
	BaseRequest
}

type DeviceModifyRequest struct {
	Id uint64 `json:"id"`
	DeviceCreateRequest
}

type ProductCreateRequest struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type ProductDeleteRequest struct {
	Id uint64 `json:"id"`
}

type ProductListBaisc struct {
	Id        uint64 `json:"id"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	CreatedAt string `json:"created_at"`
}

type ProductListReply struct {
	List  []*ProductListBaisc `json:"list"`
	Count int64               `json:"count"`
}

type ProductListRequst struct {
	BaseRequest
}

type ProductModifyRequest struct {
	Id uint64 `json:"id"`
	ProductCreateRequest
}
